### ISSUE TITLE
authentication support

### ISSUE THREAD

**Issue by segator** [erebe/wstunnel#12]
to secure the server tunnel we should be able to set credentials

wstunnel --server --credentials mycredentials.htpasswd  wss://0.0.0.0:443

then the client wstunnel wss://myuser:mypass@server:443

**Comment by erebe** [comment]
Hello,

Supporting all the possible hash for htpasswd will be a lot of work and possibly contains a lot of issues.

**Comment by erebe** [comment]
Hello,

Sorry for the late response, I haven't seen your issue in my mailbox.

Regarding your feature request, I will not implement it as I will require a lot of work in order to support all the possible hash function forhtpasswd, but also the feature you request is feasible if you setup a reverse-proxy (i.e: nginx) in front of wstunnel in order to do that.

Ok this require a bit more of work/setup than just spawning wstunnel, but the project aims to stay as simple as possible while remaining useful to bypass firewalls.
