### ISSUE TITLE
ssh configuration

### ISSUE THREAD

**Issue by manawenuz** [erebe/wstunnel#13]
I've been using mhzed/wstunnel in my setup, and been using it's -t stdio feature to use .ssh/config, the idea of a single executable binary is wonderful, and i prefer to use this project over the other, can someone help with the ProxyCommand ?
thanks

**Comment by erebe** [comment]
Hello,
I will try to give a look at it this weekend. Don't know yet if it will be difficult to implement or not.
I will let you know

**Comment by erebe** [comment]
Any news on your side ?

**Comment by erebe** [comment]
https://github.com/erebe/wstunnel/releases/tag/2.0

**Comment by feisuzhu** [comment]
Not news on his side but thank you for implementing this feature!

We are providing native ssh access to our users through HTTP tunnel but HTTP CONNECT doesn't play well with our chosen load balancer, so I searched the web and found this, the rest are either implemented in nodejs or missing this feature.

And yes, there is also a `--upgradePathPrefix` which is also a must for us.

Thank you!

**Comment by erebe** [comment]
Haha thank you very much. It took almost 3 years to get this level of feature.

If you haven't already done it, I recommend you to use the latest version 
https://github.com/erebe/wstunnel/releases/tag/v3.0
You will get better performance and a smaller memory footprint.
The release is stable now, it is still in draft only because that I am too lazy to recreate all the binary for all architectures.
