### ISSUE TITLE
Build wstunnel on ARM Android

### ISSUE THREAD

**Issue by rootergod** [erebe/wstunnel#140]
Hello
How to build wstunnel for Android?

**Comment by erebe** [comment]
Hello,

I have no idea, I never tried.
But you can try to use this script that I use to build on raspbian (raspberry pi) https://github.com/erebe/wstunnel/blob/master/build_raspbian.sh

**Comment by alirezaalj** [comment]
Hello It would be really great to be able to do it for Android as well
and run that with termux or ...
#https://github.com/oven-sh/bun/issues/423

**Comment by alou-S** [comment]
> Hello How to build wstunnel for Android?

I tried building it natively with Termux but some of the build deps are not prepackaged for Termux. I didn't bother to compile the required build deps since that's a pain.

You could rather try running it within a proot environment which should work fine witht he aarch64 build.


@erebe If you don't mine please would you add aarch64 builds to the latest release (v5) and releases thereafter? I'm actively using it. Thenku <3

**Comment by erebe** [comment]
Hello, @alou-S  sorry for the delay I missed your message.

Yes I am going to release an aarch64 release in the coming days

**Comment by erebe** [comment]
I have added it @alou-S  https://github.com/erebe/wstunnel/releases/download/v5.0/wstunnel-linux-aarch64.zip
