### ISSUE TITLE
Latency, Throughput, and Scalability?

### ISSUE THREAD

**Issue by lonnietc** [erebe/wstunnel#208]
Hello,

I have just come across wstunnel and am wondering if there are any benchmarks or information on the latency, throughput, and scalability?

I was also looking at Wireguard but not sure how wstunnel compares in terms of speed and encryption.

Any information would be greatly appreciated.
Thanks in advance

**Comment by erebe** [comment]
Hello,

Wstunnel and WireGuard does not really compare. If you can use WireGuard, please do use it. It will be better for you.
You may want to use wstunnel in addition to wireguard, if your wireguard traffic is blocked.

wstunnel is there to bypass firewall and punch a hole for you to forward/tunnel any traffic you want.
It does not pay particular attention to security. 
Also, as you are tunneling traffic over TCP, you have more overhead/jitter/latency than raw UDP. 
In terms of throughput, both should be kind of the same. 
For scalability, Wireguard should be better also as it involve less protocol overhead.

So if you can use wireguard directly, just use it. If you can't establish you wireguard traffic due to some blocking, use wstunnel (with ot without wireguard) to bypass those blocking.
