### ISSUE TITLE
An error occurs when building v.8.5.2

### ISSUE THREAD

**Issue by Zloi78** [erebe/wstunnel#209]
An error occurs when building (via cross build):

![2024-01-01_161226](https://github.com/erebe/wstunnel/assets/6129745/6fd0d4de-1450-48d1-bc6d-fad00758e993)

In versions v.8.5.0 and below, there are no problems:

_Compiling wstunnel v8.5.0 (/project)
 Finished release [optimized + debuginfo] target(s) in 4m 05s_

**Comment by erebe** [comment]
Hello,

Do you use rust 1.75 ? If not Would you mind trying with rust 1.75

**Comment by Zloi78** [comment]
Thanks.

But there is no target (mipsel-unknown-linux-musl) in version 1.75.
Okay, since the changes are not that significant, I’ll stay on version 8.5.0. :)

Happy New Year!

**Comment by erebe** [comment]
Happy new year to you too.
If you want, you can comment https://github.com/erebe/wstunnel/blob/main/src/tunnel/tls_reloader.rs#L89 this line. It will not break anything, you just not support edge case where tls certificate are not reloaded on server if you delete the files.

But besides that, everything will be ok

**Comment by vercas** [comment]
I've got my own fork of wstunnel that I've piped into my CI system, and I **sometimes** see this error as well... But not all the time. And I have absolutely no idea why.  
To add: replacing the certificates is how you should expect users to update them. It is, in fact, more difficult to replace them via traditional file overwrites, with the way Linux tools work.

**Comment by erebe** [comment]
@vercas That's a fair point regarding how users are going to update certs.

Regarding your issue in CI, that's strange because as long as you have Rust 1.75 standard lib, you should have the function. It should not be flaky.

@Zloi78 Do you know if `mipsel-unknown-linux-musl` target is going to appear at some point for Rust 1.75 ? If not I can make a cfg flags.

Just for information, after I introduce udp association, I plan to make an "LTS" version where i provide a binary for a lot more architecture than what there is today.

**Comment by erebe** [comment]
I made a new release https://github.com/erebe/wstunnel/releases/tag/v9.0.0 which does not depend on rust 1.75 anymore.
So you should be able to get rid of the patch.
