### ISSUE TITLE
Rejecting connection with not allowed destination

### ISSUE THREAD

**Issue by soudaburger** [erebe/wstunnel#284]
```json
{"...": "...", id="018fd0c5-eac9-70e1-b10d-b8a117c98173" remote="127.0.0.1:51820"}: wstunnel::tunnel::server: Rejecting connection with not allowed destination: RemoteAddr { protocol: Udp { timeout: None }, host: Ipv4(127.0.0.1), port: 51820 }
```

I am trying to use path prefixing to restrict the URIs available and exposed, but I keep running into this.  There doesn't seem to be a server-side config that's restricting domain, just prefix or "--restrict-to".  I have the server set to the following config below, am I missing something though?

```bash
# Server startup command
/usr/local/bin/wstunnel server --tls-certificate=/etc/ssl/wstunnel.crt --tls-private-key=/etc/ssl/wstunnel.key --log-lvl debug --restrict-to 127.0.0.1:51820 "wss://[::]:443" -r "blah"

# Client startup command
wstunnel client -L 'udp://51820:127.0.0.1:51820?timeout_sec=0' 'wss://my.example.com:443' --tls-sni-override my.example.com
```

**Comment by nxtreaming** [comment]
Please try to remove `-r "blah"` from your server side config.

**Comment by erebe** [comment]
feel free to re-open if needed

**Comment by gssantana** [comment]
Maybe this help for issue

I had the same error using the versions 10.1.9 e 10.1.11

I was following this article https://community.hetzner.com/tutorials/obfuscating-wireguard-using-wstunnel#step-31---android-client

And it tells to generate secret using the command `openssl rand -base64 42`, but I was always get the error bellow. I was using version 10.1.9 and after I upgrade it to 10.1.11 and I was getting the same error too

2025-05-02T15:04:04.212162Z  WARN cnx{peer="myserver:51002"}:tunnel{id="01969186-aaed-7fb3-a9e5-1ea268517006" remote="localhost:59112"}: wstunnel::tunnel::server::server: Rejecting connection with not allowed destination: RemoteAddr { protocol: Udp { timeout: None }, host: Domain("localhost"), port: 59112 }

After I tried to use the secret "123456" and everything works. So, I tought the problem is size and generate a new secret with command `openssl rand -base64 32` and everything continue work.

I am not sure secret size is the problem, but for me this was solution.
