### ISSUE TITLE
UDP not stable

### ISSUE THREAD

**Issue by gvsurenderreddy** [erebe/wstunnel#47]
Hello sir
UDP session isn't stable connection always reset on DPI network and opens new connection any solution please TCP looks solid

**Comment by erebe** [comment]
Hello,
Tunneling UDP over TCP is complicated as UDP does not have any notion of begin/end of a connection. It is just a stream of packet.

In order to not leak TCP connection when tunneling UDP traffic, every connection to the server is closed after 30sec by default.

You can change this timeout increase or disable it completely with this flag
```
     --udpTimeoutSec=INT                    When using udp forwarding,
                                            timeout in seconds after when the
                                            tunnel connection is closed.
                                            Default 30sec, -1 means no timeout
```

I would rather recommend you to set it to a high value instead of disabling it

**Comment by gvsurenderreddy** [comment]
I'm trying voip on UDP sir What would you recommend please

**Comment by gvsurenderreddy** [comment]
wstunnel: ParseException "string" i see this error 

wstunnel --server ws://0.0.0.0:8080 -r 127.0.0.1:40000 --quiet

**Comment by gvsurenderreddy** [comment]
thread blocked indefinitely in an MVar operation

**Comment by erebe** [comment]
Can you provide me a way to reproduce this ?
How do you start wstunnel server, how do you start wstunnel client ?
Is there a way to replay some traffic to trigger the issue ?
Does the issue appear every time ?

**Comment by gvsurenderreddy** [comment]
Server wstunnel --server ws://0.0.0.0:8080 -r 127.0.0.1:40000 -q
sudo nohup wstunnel --udp  --udpTimeoutSec=-1 -L 127.0.0.1:3333:127.0.0.1:40000 ws://116.203.140.183:8080 --quiet &

I need to reboot Server and Client to make it work there is no way to that Client send ACK to Server and try to connect every 3s or something like other tunnel program does sir .

**Comment by Ajju2211** [comment]
I am also setting up  Asterix VOIp  tunneling through wstunnel.
Please help me out.
