### ISSUE TITLE
UDP timeout does not work in some cases

### ISSUE THREAD

**Issue by CSd4FSMP** [erebe/wstunnel#86]
Since the network can only transmit TCP, use wstunnel for the game
But there is a problem, UDP timeout does not work at some times

example: 2games

csgo and apex legends
**csgo opens a socket for each UDP**
![csgo-udp](https://user-images.githubusercontent.com/76765608/131257743-8b0ef751-06ec-453b-99a1-edca45418768.png)
RemoteIP / Local Port / Remote Port

**But apex legends will reuse one UDP socket to communicate with any remote IP**
![apex-udp](https://user-images.githubusercontent.com/76765608/131257735-1598bc08-8c94-47d5-b3ff-ade1a62886e1.png)
RemoteIP / Local Port / Remote Port

Set --udpTimeoutSec=60 at this time
csgo is normal, but apex legends will disconnected in 60 seconds on time

timeout logs:
DEBUG :: Oppening tcp connection to XXX
DEBUG :: Doing tls Handshake
DEBUG :: Oppening Websocket stream
DEBUG :: TIMEOUT connection

If set --udpTimeoutSec=-1
any game will work fine, but some games will generate thousands of TCP connections

**Comment by erebe** [comment]
Well, you can't have both behavior at the same time ¯\_(ツ)_/¯

just put `--udpTimeoutSec=-1` and restart wstunnel between 2 games

**Comment by seth-hunter** [comment]
@erebe, instead of just "timing out" 60 seconds after creation, shouldn't the timeout be since last activity?  That seems as thought it would elegantly address @CSd4FSMP's issue without requiring  the hack of -1 and periodic restarts.  I ran into this same issue today, would much prefer a "since last activity"-based timeout rather than current "since tunnel created" behavior.
